---
- name: Setup Nginx Web Server
  hosts: all
  become: true
  vars:
    nginx_version: 1.18.0
  tasks:
  - name: Update the system
    yum:
      name: '*'
      state: latest
  - name: Install Nginx
    yum:
      name: nginx-{{ nginx_version }}
      state: present
  - name: Create Nginx configuration file
    template:
      src: templates/nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: 0644
  - name: Start Nginx service
    service:
      name: nginx
      state: started
      enabled: true

